http://localhost:3000/ 


###
 http://localhost:3000/contacts

###
http://localhost:3000/contacts/682b2f4cee8a9b21a27e3535

{
  "_id": "682b2f4cee8a9b21a27e3535",
  "firstName": "Pulane",
  "lastName": "Mabula",
  "email": "pulane@edu.com",
  "favoriteColor": "blue",
  "birthday": "1990-06-21"
}


###
http://localhost:3000/contacts/682b30cdee8a9b21a27e3536


{
  "_id": "682b30cdee8a9b21a27e3536",
  "firstName": "paballo",
  "lastName": "Johnson",
  "email": "Pabij@example.com",
  "favoriteColor": "blue",
  "birthday": "1992-01-23"
}
###


POST http://localhost:3000/contacts/ HTTP/1.1
Content-Type: application/json

  {
    "firstName": "sope",
    "lastName": "Mojafy",
    "email": "Awelolea@edu.com",
    "favoriteColor": "Yello",
    "birthday": "1983-12-15"
  }
###

PUT http://localhost:3000/contacts/682cfdb7eb52eca3598b3ff7
Content-Type: application/json

  {
    "firstName": "Molile",
    "lastName": "Mosia",
    "email": "Mosia@edu.com",
    "favoriteColor": "Yello",
    "birthday": "1983-2-15"
  }

###

DELETE http://localhost:3000/contacts/6839aac1e22f3b69b405a7e0
Content-Type: application/json



### Production

https://cse341-project-m68u.onrender.com/

###

https://cse341-project-m68u.onrender.com/contacts

###

https://cse341-project-m68u.onrender.com/contacts/682b30cdee8a9b21a27e3536

{
  "_id": "682b30cdee8a9b21a27e3536",
  "firstName": "paballo",
  "lastName": "Johnson",
  "email": "Pabij@example.com",
  "favoriteColor": "blue",
  "birthday": "1992-01-23"
}
###

https://cse341-project-m68u.onrender.com/contacts/682b2f4cee8a9b21a27e3535


{
  "_id": "682b2f4cee8a9b21a27e3535",
  "firstName": "Pulane",
  "lastName": "Mabula",
  "email": "pulane@edu.com",
  "favoriteColor": "blue",
  "birthday": "1990-06-21"
}